okta:
  domain: ${OKTA_DOMAIN}  # or hardcode: your-company.okta.com
  api_token: ${OKTA_API_TOKEN}

grafana:
  url: ${GRAFANA_URL}  # e.g., https://grafana.example.com
  api_key: ${GRAFANA_API_KEY}

sync:
  interval_seconds: 300  # Run every 5 minutes
  dry_run: false  # Set true to preview changes without applying
  mappings:
    - okta_group: "Engineering"
      grafana_team: "Engineers"
      grafana_role: "Viewer"  # Optional: Admin, Editor, or Viewer (default)
    - okta_group: "DataScience"
      grafana_team: "Data Scientists"
      grafana_role: "Editor"  # Grant Editor role to Data Science team
    - okta_group: "SRE"
      grafana_team: "SRE Team"
      grafana_role: "Admin"  # Grant Admin role to SRE team

  # Optional: Okta groups whose members should have Grafana admin privileges
  # Users in these groups will be granted isGrafanaAdmin=true
  # Users not in any of these groups will have admin privileges revoked
  admin_groups:
    - "Grafana-Admins"
    - "Platform-Team"

logging:
  level: INFO  # DEBUG, INFO, WARNING, ERROR, CRITICAL
  format: json  # json or text

metrics:
  enabled: false  # Set true to enable Prometheus metrics
  port: 8000      # Port for metrics and health endpoint
  host: 0.0.0.0   # Host to bind metrics server (0.0.0.0 for all interfaces)
