okta:
  domain: ${OKTA_DOMAIN}  # or hardcode: your-company.okta.com
  api_token: ${OKTA_API_TOKEN}

grafana:
  url: ${GRAFANA_URL}  # e.g., https://grafana.example.com
  api_key: ${GRAFANA_API_KEY}

sync:
  interval_seconds: 300  # Run every 5 minutes
  dry_run: false  # Set true to preview changes without applying
  mappings:
    - okta_group: "Engineering"
      grafana_team: "Engineers"
    - okta_group: "DataScience"
      grafana_team: "Data Scientists"
    - okta_group: "SRE"
      grafana_team: "SRE Team"

logging:
  level: INFO  # DEBUG, INFO, WARNING, ERROR, CRITICAL
  format: json  # json or text
