okta:
  domain: ${OKTA_DOMAIN}  # or hardcode: your-company.okta.com

  # Authentication method: "api_token" or "oauth"
  auth_method: api_token  # Default: api_token

  # API Token authentication (default method)
  api_token: ${OKTA_API_TOKEN}

  # OAuth 2.0 authentication (recommended for production)
  # Uncomment and configure if using oauth auth_method
  # oauth:
  #   client_id: ${OKTA_CLIENT_ID}
  #   token_endpoint_auth_method: private_key_jwt  # or client_secret_basic
  #
  #   # For client_secret_basic/client_secret_post:
  #   # client_secret: ${OKTA_CLIENT_SECRET}
  #
  #   # For private_key_jwt (required by some Okta orgs):
  #   private_key_path: ${OKTA_PRIVATE_KEY_PATH}  # Path to private.pem
  #
  #   # Optional: JWT Key ID (kid) for JWT header when using private_key_jwt
  #   # If not specified, Okta will match the public key by signature verification
  #   # jwt_key_id: ${OKTA_JWT_KEY_ID}
  #
  #   scopes:
  #     - okta.groups.read
  #     - okta.users.read

grafana:
  url: ${GRAFANA_URL}  # e.g., https://grafana.example.com
  api_key: ${GRAFANA_API_KEY}

sync:
  interval_seconds: 300  # Run every 5 minutes
  dry_run: false  # Set true to preview changes without applying
  mappings:
    - okta_group: "Engineering"
      grafana_team: "Engineers"
      grafana_role: "Viewer"  # Optional: Admin, Editor, or Viewer (default)
    - okta_group: "DataScience"
      grafana_team: "Data Scientists"
      grafana_role: "Editor"  # Grant Editor role to Data Science team
    - okta_group: "SRE"
      grafana_team: "SRE Team"
      grafana_role: "Admin"  # Grant Admin role to SRE team

  # Optional: Okta groups whose members should have Grafana admin privileges
  # Users in these groups will be granted isGrafanaAdmin=true
  # Users not in any of these groups will have admin privileges revoked
  admin_groups:
    - "Grafana-Admins"
    - "Platform-Team"

logging:
  level: INFO  # DEBUG, INFO, WARNING, ERROR, CRITICAL
  format: json  # json or text

metrics:
  enabled: false  # Set true to enable Prometheus metrics
  port: 8000      # Port for metrics and health endpoint
  host: 0.0.0.0   # Host to bind metrics server (0.0.0.0 for all interfaces)
