# Default values for gots

image:
  repository: cropalato/gots
  pullPolicy: Always  # Use Always for latest tag to ensure newest image is pulled
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

# Resources allocation
resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

# Restart policy for the deployment
restartPolicy: Always

# Node selector for pod assignment
nodeSelector: {}

# Tolerations for pod assignment
tolerations: []

# Affinity for pod assignment
affinity: {}

# Extra environment variables to add to the container
extraEnv: []
# Example:
# - name: LOG_LEVEL
#   value: "DEBUG"
# - name: CUSTOM_VAR
#   value: "custom-value"
# - name: SECRET_VAR
#   valueFrom:
#     secretKeyRef:
#       name: my-secret
#       key: my-key

# Okta configuration
okta:
  domain: ""  # e.g., "company.okta.com"

  # Authentication method: "api_token" or "oauth"
  authMethod: "api_token"

  # API Token authentication (when authMethod = "api_token")
  apiToken: ""  # Okta API token (will be stored in Secret)

  # OAuth 2.0 authentication (when authMethod = "oauth")
  oauth:
    clientId: ""  # OAuth client ID
    tokenEndpointAuthMethod: "client_secret_basic"  # or "private_key_jwt"

    # For client_secret_* methods
    clientSecret: ""  # OAuth client secret (will be stored in Secret)

    # For private_key_jwt method
    privateKey: ""  # Private key PEM content (will be stored in Secret)
    # Alternatively, use privateKeySecretName to reference an existing secret
    privateKeySecretName: ""  # Name of existing secret containing private key
    privateKeySecretKey: "private.pem"  # Key in the secret

    # Optional: JWT Key ID (kid) for private_key_jwt method
    # If not specified, Okta will match the public key by signature verification
    jwtKeyId: ""  # e.g., "eadE2YW30tucVX8l61Re-cNXAfeQVxq9U_LJ6SXpW00"

    scopes:
      - okta.groups.read
      - okta.users.read

# Grafana configuration
grafana:
  url: ""  # e.g., "https://grafana.company.com"
  apiKey: ""  # Grafana API key (will be stored in Secret)

# Sync configuration
sync:
  intervalSeconds: 3600  # Sync every hour
  dryRun: false
  # admin_groups: []  # Optional: Okta groups that grant Grafana admin privileges
  # Example:
  # - "Grafana-Admins"
  # - "Platform-Team"
  mappings: []
  # Example mappings:
  # - okta_group: "Engineering"
  #   grafana_team: "Engineering"
  # - okta_group: "DevOps"
  #   grafana_team: "DevOps"
