apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gots.fullname" . }}
  labels:
    {{- include "gots.labels" . | nindent 4 }}
type: Opaque
stringData:
  OKTA_API_TOKEN: {{ .Values.okta.apiToken | quote }}
  GRAFANA_API_KEY: {{ .Values.grafana.apiKey | quote }}
