apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gots.fullname" . }}
  labels:
    {{- include "gots.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if eq .Values.okta.authMethod "api_token" }}
  OKTA_API_TOKEN: {{ .Values.okta.apiToken | quote }}
  {{- else if eq .Values.okta.authMethod "oauth" }}
  OKTA_CLIENT_ID: {{ .Values.okta.oauth.clientId | quote }}
  {{- if .Values.okta.oauth.clientSecret }}
  OKTA_CLIENT_SECRET: {{ .Values.okta.oauth.clientSecret | quote }}
  {{- end }}
  {{- if and .Values.okta.oauth.privateKey (not .Values.okta.oauth.privateKeySecretName) }}
  OKTA_PRIVATE_KEY: {{ .Values.okta.oauth.privateKey | quote }}
  {{- end }}
  {{- if .Values.okta.oauth.jwtKeyId }}
  OKTA_JWT_KEY_ID: {{ .Values.okta.oauth.jwtKeyId | quote }}
  {{- end }}
  {{- end }}
  GRAFANA_API_KEY: {{ .Values.grafana.apiKey | quote }}
